name: factor_research
channels:
  - anaconda
  - conda-forge
  - quantopian
  - defaults
dependencies:
  - alembic=0.7.7
  - alphalens=0.3.6
  - asn1crypto=0.24.0
  - atk=2.25.90
  - backcall=0.1.0
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports.shutil_get_terminal_size=1.0.0
  - backports_abc=0.5
  - bcolz=0.12.1
  - blas=1.0
  - bleach=3.1.0
  - blosc=1.15.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - cairo=1.14.12
  - certifi=2018.11.29
  - cffi=1.12.1
  - chardet=3.0.4
  - click=7.0
  - configparser=3.7.1
  - contextlib2=0.5.5
  - cryptography=2.5
  - cycler=0.10.0
  - cyordereddict=0.2.2
  - cython=0.29.5
  - dbus=1.13.2
  - decorator=4.3.2
  - defusedxml=0.5.0
  - empyrical=0.5.0
  - entrypoints=0.3
  - enum34=1.1.6
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.9.1
  - functools32=3.2.3.2
  - futures=3.2.0
  - gdk-pixbuf=2.36.12
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=6.1.2
  - gobject-introspection=1.56.1
  - graphite2=1.3.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gtk2=2.24.31
  - harfbuzz=1.9.0
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.8
  - intel-openmp=2019.1
  - intervaltree=2.1.0
  - ipaddress=1.0.22
  - ipykernel=4.10.0
  - ipython=4.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.3
  - jinja2=2.10
  - jpeg=9c
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=5.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libffi=3.2.1
  - libgcc-ng=7.3.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.16
  - libstdcxx-ng=7.3.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - logbook=0.12.5
  - lru-dict=1.1.4
  - lxml=4.3.0
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=2.2.2
  - mistune=0.8.4
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - multipledispatch=0.6.0
  - nbconvert=5.4.1
  - nbformat=4.4.0
  - ncurses=6.1
  - networkx=1.11
  - notebook=5.7.4
  - numexpr=2.6.8
  - numpy=1.11.3
  - numpy-base=1.15.0
  - openssl=1.1.1
  - pandas=0.21.1
  - pandas-datareader=0.7.0
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - pango=1.40.14
  - parso=0.3.4
  - pathlib2=2.3.3
  - patsy=0.5.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=19.0.3
  - pixman=0.34.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pyqt=5.6.0
  - pysocks=1.6.8
  - pytables=3.4.4
  - python=2.7.15
  - python-dateutil=2.8.0
  - pytz=2018.9
  - pyyaml=3.13
  - pyzmq=18.0.0
  - qt=5.6.3
  - qtconsole=4.4.3
  - readline=7.0
  - requests=2.21.0
  - requests-file=1.4.3
  - scandir=1.9.0
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.8.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.18.1
  - six=1.12.0
  - snappy=1.1.7
  - sortedcontainers=1.4.4
  - sqlalchemy=1.2.18
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - subprocess32=3.5.3
  - terminado=0.8.1
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=5.1.1
  - trading-calendars=1.6.1
  - traitlets=4.3.2
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - widgetsnbextension=3.4.2
  - wrapt=1.11.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipline=1.3.0
  - zlib=1.2.11
  - pip:
    - mako==1.0.7

