name: ml4t
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.6.3
  - bottleneck=1.2.1
  - cloudpickle=0.6.1
  - colorlover=0.2.1
  - cytoolz=0.9.0.1
  - dask-core=1.0.0
  - empyrical=0.3.4
  - entrypoints=0.2.3
  - fribidi=1.0.5
  - graphite2=1.3.13
  - harfbuzz=1.9.0
  - imageio=2.4.1
  - ipydatawidgets=4.0.0
  - ipyscales=0.3.0
  - ipyvolume=0.5.1
  - ipywebrtc=0.4.3
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.0
  - libxslt=1.1.32
  - networkx=2.2
  - pexpect=4.6.0
  - pixman=0.34.0
  - ptyprocess=0.6.0
  - pyopenssl=18.0.0
  - python-graphviz=0.8.4
  - pythreejs=2.0.2
  - pywavelets=1.0.1
  - pyyaml=3.13
  - scikit-image=0.14.1
  - setuptools=40.6.3
  - terminado=0.8.1
  - toolz=0.9.0
  - traitlets=4.3.2
  - traittypes=0.2.1
  - umap-learn=0.3.7
  - wheel=0.32.3
  - yaml=0.1.7
  - arrow-cpp=0.11.1
  - asn1crypto=0.24.0
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - autopep8=1.4.3
  - backcall=0.1.0
  - binutils_impl_linux-64=2.28.1
  - binutils_linux-64=7.2.0
  - blas=1.0
  - bleach=3.0.2
  - blosc=1.14.4
  - bokeh=1.0.2
  - boto=2.49.0
  - boto3=1.9.66
  - botocore=1.12.67
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.4.2
  - cycler=0.10.0
  - dbus=1.13.2
  - decorator=4.3.0
  - docutils=0.14
  - expat=2.2.6
  - fastparquet=0.1.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gcc_impl_linux-64=7.2.0
  - gcc_linux-64=7.2.0
  - gflags=2.2.2
  - glib=2.56.2
  - glog=0.3.5
  - gmp=6.1.2
  - graphviz=2.40.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.2.0
  - gxx_linux-64=7.2.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - inflection=0.3.1
  - intel-openmp=2019.1
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - jedi=0.13.2
  - jinja2=2.10
  - jmespath=0.9.3
  - joblib=0.13.0
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - libboost=1.67.0
  - libedit=3.1.20170329
  - libevent=2.1.8
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libgpuarray=0.7.6
  - libpng=1.6.35
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - lightgbm=2.2.1
  - llvmlite=0.26.0
  - lxml=4.2.5
  - lz4-c=1.8.1.2
  - lzo=2.10
  - mako=1.0.7
  - markupsafe=1.1.0
  - matplotlib=3.0.2
  - mistune=0.8.4
  - mkl=2019.1
  - mkl-service=1.1.2
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - more-itertools=4.3.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.8.2
  - nltk=3.4
  - notebook=5.7.4
  - numba=0.41.0
  - numexpr=2.6.8
  - numpy=1.15.4
  - numpy-base=1.15.4
  - olefile=0.46
  - openssl=1.1.1a
  - packaging=18.0
  - pandas=0.23.4
  - pandas-datareader=0.7.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.3.1
  - patsy=0.5.1
  - pcre=8.42
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=18.1
  - plotly=3.4.2
  - pluggy=0.8.0
  - prometheus_client=0.5.0
  - prompt_toolkit=2.0.7
  - py=1.7.0
  - pyarrow=0.11.1
  - pycodestyle=2.4.0
  - pycparser=2.19
  - pygments=2.3.1
  - pygpu=0.7.6
  - pymc3=3.5
  - pyparsing=2.3.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - pytables=3.4.4
  - pytest=4.0.2
  - python-dateutil=2.7.5
  - pytz=2018.7
  - pyzmq=17.1.2
  - qt=5.9.7
  - qtconsole=4.4.3
  - quandl=3.4.5
  - readline=7.0
  - requests=2.21.0
  - retrying=1.3.3
  - s3transfer=0.1.13
  - scikit-learn=0.20.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - sip=4.19.8
  - six=1.12.0
  - smart_open=1.7.1
  - snappy=1.1.7
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - testpath=0.4.2
  - theano=1.0.2
  - thrift=0.11.0
  - thrift-cpp=0.11.0
  - tk=8.6.8
  - tornado=5.1.1
  - tqdm=4.28.1
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.4.2
  - wrapt=1.10.11
  - xlrd=1.2.0
  - xz=5.2.4
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.3.3
  - pytorch=1.0.0
  - torchvision=0.2.1
  - pip:
    - bz2file==0.98
    - cython==0.29.2
    - dask==1.0.0
    - gensim==3.6.0
    - hdbscan==0.8.18
    - pyfinance==1.1.1
    - tables==3.4.4
    - torch==1.0.0
    - xmltodict==0.11.0
